
version: '2.1'
services:
  authority0:
    build:
      context: .
      dockerfile: docker_authority/Dockerfile
      args:
        PARITY_VERSION: ${PARITY_VERSION}
        NETWORK_NAME: ${NETWORK_NAME}
        ID: 0
    volumes:
      - data-volume:/home/parity/.local/share/io.parity.ethereum/chains/${NETWORK_NAME}/db
    command:
      --config parity/config/authority.toml
      --engine-signer 0x00bd138abd70e2f00903268f3db08f2d25677c9e
      --ws-interface 0.0.0.0
      --unsafe-expose
      --jsonrpc-cors all
      --no-persistent-txqueue
      --fast-unlock
      --tracing on
    ports:
      - 8545:8545
      - 8546:8546
      - 8180:8180
      - 30303:30303
    networks:
      app_net:
        ipv4_address: 172.16.0.10


  authority1:
    build:
      context: .
      dockerfile: docker_authority/Dockerfile
      args:
        PARITY_VERSION: ${PARITY_VERSION}
        NETWORK_NAME: ${NETWORK_NAME}
        ID: 1
    command:
      --config parity/config/authority.toml
      --engine-signer 0x00aa39d30f0d20ff03a22ccfc30b7efbfca597c2
      --ws-interface 0.0.0.0
      --unsafe-expose
      --jsonrpc-cors all
      --no-persistent-txqueue
      --fast-unlock
    ports:
      - 8555:8545
      - 8556:8546
    networks:
      app_net:
        ipv4_address: 172.16.0.11


  authority2:
    build:
      context: .
      dockerfile: docker_authority/Dockerfile
      args:
        PARITY_VERSION: ${PARITY_VERSION}
        NETWORK_NAME: ${NETWORK_NAME}
        ID: 2
    command:
      --config parity/config/authority.toml
      --engine-signer 0x002e28950558fbede1a9675cb113f0bd20912019
      --no-persistent-txqueue
      --fast-unlock
    ports:
      - 8565:8545
      - 8566:8546
    networks:
      app_net:
        ipv4_address: 172.16.0.12


  authority3:
    build:
      context: .
      dockerfile: docker_authority/Dockerfile
      args:
        PARITY_VERSION: ${PARITY_VERSION}
        NETWORK_NAME: ${NETWORK_NAME}
        ID: 3
    command:
      --config parity/config/authority.toml
      --engine-signer 0xa0255b4e2030c9fe962eceacf76ae5f31fe3c441
      --no-persistent-txqueue
      --fast-unlock
    ports:
      - 8575:8545
      - 8576:8546
    networks:
      app_net:
        ipv4_address: 172.16.0.13


  authority4:
    build:
      context: .
      dockerfile: docker_authority/Dockerfile
      args:
        PARITY_VERSION: ${PARITY_VERSION}
        NETWORK_NAME: ${NETWORK_NAME}
        ID: 4
    command:
      --config parity/config/authority.toml
      --engine-signer 0xcc9cef482b9378513bbb51e00838409d30a5c497
      --no-persistent-txqueue
      --fast-unlock
    ports:
      - 8585:8545
      - 8586:8546
    networks:
      app_net:
        ipv4_address: 172.16.0.14


  authority5:
    build:
      context: .
      dockerfile: docker_authority/Dockerfile
      args:
        PARITY_VERSION: ${PARITY_VERSION}
        NETWORK_NAME: ${NETWORK_NAME}
        ID: 5
    command:
      --config parity/config/authority.toml
      --engine-signer 0xa5b418995661512d06581506e43ad0222a4822e5
      --no-persistent-txqueue
      --fast-unlock
    ports:
      - 8595:8545
      - 8596:8546
    networks:
      app_net:
        ipv4_address: 172.16.0.15


  authority6:
    build:
      context: .
      dockerfile: docker_authority/Dockerfile
      args:
        PARITY_VERSION: ${PARITY_VERSION}
        NETWORK_NAME: ${NETWORK_NAME}
        ID: 6
    command:
      --config parity/config/authority.toml
      --engine-signer 0x2fe5bd43cc2b5209f9aa39cbc5ecdbc085b0a939
      --no-persistent-txqueue
      --fast-unlock
    ports:
      - 8605:8545
      - 8606:8546
    networks:
      app_net:
        ipv4_address: 172.16.0.16


  authority7:
    build:
      context: .
      dockerfile: docker_authority/Dockerfile
      args:
        PARITY_VERSION: ${PARITY_VERSION}
        NETWORK_NAME: ${NETWORK_NAME}
        ID: 7
    command:
      --config parity/config/authority.toml
      --engine-signer 0x302423184bac5ef0fe9235b0af724bf06cfa87b6
      --no-persistent-txqueue
      --fast-unlock
    ports:
      - 8615:8545
      - 8616:8546
    networks:
      app_net:
        ipv4_address: 172.16.0.17


  authority8:
    build:
      context: .
      dockerfile: docker_authority/Dockerfile
      args:
        PARITY_VERSION: ${PARITY_VERSION}
        NETWORK_NAME: ${NETWORK_NAME}
        ID: 8
    command:
      --config parity/config/authority.toml
      --engine-signer 0x818f463f6ce0c6db4d536a9e5c39146fef6f50d1
      --no-persistent-txqueue
      --fast-unlock
    ports:
      - 8625:8545
      - 8626:8546
    networks:
      app_net:
        ipv4_address: 172.16.0.18


  authority9:
    build:
      context: .
      dockerfile: docker_authority/Dockerfile
      args:
        PARITY_VERSION: ${PARITY_VERSION}
        NETWORK_NAME: ${NETWORK_NAME}
        ID: 9
    command:
      --config parity/config/authority.toml
      --engine-signer 0x6752ab464fa87c91f8813b696dcbb1fb7b3142cb
      --no-persistent-txqueue
      --fast-unlock
    ports:
      - 8635:8545
      - 8636:8546
    networks:
      app_net:
        ipv4_address: 172.16.0.19


  authority10:
    build:
      context: .
      dockerfile: docker_authority/Dockerfile
      args:
        PARITY_VERSION: ${PARITY_VERSION}
        NETWORK_NAME: ${NETWORK_NAME}
        ID: 10
    command:
      --config parity/config/authority.toml
      --engine-signer 0x73864c28199d1d98625e8422c62ee41d961e80c5
      --no-persistent-txqueue
      --fast-unlock
    ports:
      - 8645:8545
      - 8646:8546
    networks:
      app_net:
        ipv4_address: 172.16.0.20


  authority11:
    build:
      context: .
      dockerfile: docker_authority/Dockerfile
      args:
        PARITY_VERSION: ${PARITY_VERSION}
        NETWORK_NAME: ${NETWORK_NAME}
        ID: 11
    command:
      --config parity/config/authority.toml
      --engine-signer 0x54b4f8555d3c73ae1f41fb82a84d31d000b03d4a
      --no-persistent-txqueue
      --fast-unlock
    ports:
      - 8655:8545
      - 8656:8546
    networks:
      app_net:
        ipv4_address: 172.16.0.21


  authority12:
    build:
      context: .
      dockerfile: docker_authority/Dockerfile
      args:
        PARITY_VERSION: ${PARITY_VERSION}
        NETWORK_NAME: ${NETWORK_NAME}
        ID: 12
    command:
      --config parity/config/authority.toml
      --engine-signer 0x6a62ba8931c91e006e67ffb9fbbe7ab225aa2082
      --no-persistent-txqueue
      --fast-unlock
    ports:
      - 8665:8545
      - 8666:8546
    networks:
      app_net:
        ipv4_address: 172.16.0.22


  authority13:
    build:
      context: .
      dockerfile: docker_authority/Dockerfile
      args:
        PARITY_VERSION: ${PARITY_VERSION}
        NETWORK_NAME: ${NETWORK_NAME}
        ID: 13
    command:
      --config parity/config/authority.toml
      --engine-signer 0xcaa052ad956f5fd001ce020f6ff9114d3b663ba1
      --no-persistent-txqueue
      --fast-unlock
    ports:
      - 8675:8545
      - 8676:8546
    networks:
      app_net:
        ipv4_address: 172.16.0.23


  authority14:
    build:
      context: .
      dockerfile: docker_authority/Dockerfile
      args:
        PARITY_VERSION: ${PARITY_VERSION}
        NETWORK_NAME: ${NETWORK_NAME}
        ID: 14
    command:
      --config parity/config/authority.toml
      --engine-signer 0x62691d96c1993cdd16343cc91f3403d257765a50
      --no-persistent-txqueue
      --fast-unlock
    ports:
      - 8685:8545
      - 8686:8546
    networks:
      app_net:
        ipv4_address: 172.16.0.24


  authority15:
    build:
      context: .
      dockerfile: docker_authority/Dockerfile
      args:
        PARITY_VERSION: ${PARITY_VERSION}
        NETWORK_NAME: ${NETWORK_NAME}
        ID: 15
    command:
      --config parity/config/authority.toml
      --engine-signer 0x81b95a27affcb1d7d074c9746324241b4d000beb
      --no-persistent-txqueue
      --fast-unlock
    ports:
      - 8695:8545
      - 8696:8546
    networks:
      app_net:
        ipv4_address: 172.16.0.25


  authority16:
    build:
      context: .
      dockerfile: docker_authority/Dockerfile
      args:
        PARITY_VERSION: ${PARITY_VERSION}
        NETWORK_NAME: ${NETWORK_NAME}
        ID: 16
    command:
      --config parity/config/authority.toml
      --engine-signer 0x4f48de323699fe6eaa208da9e843d21b352b1a3d
      --no-persistent-txqueue
      --fast-unlock
    ports:
      - 8705:8545
      - 8706:8546
    networks:
      app_net:
        ipv4_address: 172.16.0.26


  authority17:
    build:
      context: .
      dockerfile: docker_authority/Dockerfile
      args:
        PARITY_VERSION: ${PARITY_VERSION}
        NETWORK_NAME: ${NETWORK_NAME}
        ID: 17
    command:
      --config parity/config/authority.toml
      --engine-signer 0xa8ccb87fab0bb4396f18ed6dd360834e0941084c
      --no-persistent-txqueue
      --fast-unlock
    ports:
      - 8715:8545
      - 8716:8546
    networks:
      app_net:
        ipv4_address: 172.16.0.27


  authority18:
    build:
      context: .
      dockerfile: docker_authority/Dockerfile
      args:
        PARITY_VERSION: ${PARITY_VERSION}
        NETWORK_NAME: ${NETWORK_NAME}
        ID: 18
    command:
      --config parity/config/authority.toml
      --engine-signer 0x6d781742953d8f6a3b1cd0f0eaae6f0a3937fa21
      --no-persistent-txqueue
      --fast-unlock
    ports:
      - 8725:8545
      - 8726:8546
    networks:
      app_net:
        ipv4_address: 172.16.0.28


  authority19:
    build:
      context: .
      dockerfile: docker_authority/Dockerfile
      args:
        PARITY_VERSION: ${PARITY_VERSION}
        NETWORK_NAME: ${NETWORK_NAME}
        ID: 19
    command:
      --config parity/config/authority.toml
      --engine-signer 0x8a4d3c100ccbc16d4db289bdd8ce8c67221f9752
      --no-persistent-txqueue
      --fast-unlock
    ports:
      - 8735:8545
      - 8736:8546
    networks:
      app_net:
        ipv4_address: 172.16.0.29


  authority20:
    build:
      context: .
      dockerfile: docker_authority/Dockerfile
      args:
        PARITY_VERSION: ${PARITY_VERSION}
        NETWORK_NAME: ${NETWORK_NAME}
        ID: 20
    command:
      --config parity/config/authority.toml
      --engine-signer 0x4772bc364922e9e5cb2fca89ee6058918d973936
      --no-persistent-txqueue
      --fast-unlock
    ports:
      - 8745:8545
      - 8746:8546
    networks:
      app_net:
        ipv4_address: 172.16.0.30


  monitor:
    image: buythewhale/ethstats_monitor
    volumes:
      - ./monitor/app.json:/home/ethnetintel/eth-net-intelligence-api/app.json:ro
    networks:
      app_net:
        ipv4_address: 172.16.0.100


  dashboard:
    image: buythewhale/ethstats
    volumes:
      - ./dashboard/ws_secret.json:/eth-netstats/ws_secret.json:ro
    ports:
      - 3001:3000
    networks:
      app_net:
        ipv4_address: 172.16.0.200

volumes:
  data-volume:
networks:
  app_net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.16.0.1/24
        gateway: 172.16.0.1
