
version: '3.5'

networks:
  02-docker_parity_net:
    external: true

services:

  netting-server:
    build:
      context: .
      dockerfile: netting-entity/Dockerfile
    command: yarn run-netting-entity -p 3000 -i 60000
    ports:
      - "3000:3000"
    networks:
      - 02-docker_parity_net


  mongo-1:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - 02-docker_parity_net

  mongo-2:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - 02-docker_parity_net

  mongo-3:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - 02-docker_parity_net

  mongo-4:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - 02-docker_parity_net

  mongo-5:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - 02-docker_parity_net

  mongo-6:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - 02-docker_parity_net

  mongo-7:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - 02-docker_parity_net

  mongo-8:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - 02-docker_parity_net

  mongo-9:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - 02-docker_parity_net

  mongo-10:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - 02-docker_parity_net


  household-server-1:
    build:
      context: .
      dockerfile: household-processing-unit/Dockerfile
    command: yarn run-server -p 3002 -P node1 -n authority_1 -d mongodb://mongo-1:27017 -N http://netting-server:3000
    ports:
      - "3002:3002"
    depends_on:
      - mongo-1
      - netting-server
    networks:
      - 02-docker_parity_net

  household-server-2:
    build:
      context: .
      dockerfile: household-processing-unit/Dockerfile
    command: yarn run-server -p 3002 -P node2 -n authority_2 -d mongodb://mongo-2:27017 -N http://netting-server:3000
    ports:
      - "3003:3002"
    depends_on:
      - mongo-2
      - netting-server
    networks:
      - 02-docker_parity_net

  household-server-3:
    build:
      context: .
      dockerfile: household-processing-unit/Dockerfile
    command: yarn run-server -p 3002 -P node3 -n authority_3 -d mongodb://mongo-3:27017 -N http://netting-server:3000
    ports:
      - "3004:3002"
    depends_on:
      - mongo-3
      - netting-server
    networks:
      - 02-docker_parity_net

  household-server-4:
    build:
      context: .
      dockerfile: household-processing-unit/Dockerfile
    command: yarn run-server -p 3002 -P node4 -n authority_4 -d mongodb://mongo-4:27017 -N http://netting-server:3000
    ports:
      - "3005:3002"
    depends_on:
      - mongo-4
      - netting-server
    networks:
      - 02-docker_parity_net

  household-server-5:
    build:
      context: .
      dockerfile: household-processing-unit/Dockerfile
    command: yarn run-server -p 3002 -P node5 -n authority_5 -d mongodb://mongo-5:27017 -N http://netting-server:3000
    ports:
      - "3006:3002"
    depends_on:
      - mongo-5
      - netting-server
    networks:
      - 02-docker_parity_net

  household-server-6:
    build:
      context: .
      dockerfile: household-processing-unit/Dockerfile
    command: yarn run-server -p 3002 -P node6 -n authority_6 -d mongodb://mongo-6:27017 -N http://netting-server:3000
    ports:
      - "3007:3002"
    depends_on:
      - mongo-6
      - netting-server
    networks:
      - 02-docker_parity_net

  household-server-7:
    build:
      context: .
      dockerfile: household-processing-unit/Dockerfile
    command: yarn run-server -p 3002 -P node7 -n authority_7 -d mongodb://mongo-7:27017 -N http://netting-server:3000
    ports:
      - "3008:3002"
    depends_on:
      - mongo-7
      - netting-server
    networks:
      - 02-docker_parity_net

  household-server-8:
    build:
      context: .
      dockerfile: household-processing-unit/Dockerfile
    command: yarn run-server -p 3002 -P node8 -n authority_8 -d mongodb://mongo-8:27017 -N http://netting-server:3000
    ports:
      - "3009:3002"
    depends_on:
      - mongo-8
      - netting-server
    networks:
      - 02-docker_parity_net

  household-server-9:
    build:
      context: .
      dockerfile: household-processing-unit/Dockerfile
    command: yarn run-server -p 3002 -P node9 -n authority_9 -d mongodb://mongo-9:27017 -N http://netting-server:3000
    ports:
      - "3010:3002"
    depends_on:
      - mongo-9
      - netting-server
    networks:
      - 02-docker_parity_net

  household-server-10:
    build:
      context: .
      dockerfile: household-processing-unit/Dockerfile
    command: yarn run-server -p 3002 -P node10 -n authority_10 -d mongodb://mongo-10:27017 -N http://netting-server:3000
    ports:
      - "3011:3002"
    depends_on:
      - mongo-10
      - netting-server
    networks:
      - 02-docker_parity_net


  sensor-server-1:
    build:
      context: .
      dockerfile: mock-sensor/Dockerfile
    command: yarn run-sensor -h household-server-1 -p 3002 -e +
    depends_on:
      - household-server-1
    networks:
      - 02-docker_parity_net

  sensor-server-2:
    build:
      context: .
      dockerfile: mock-sensor/Dockerfile
    command: yarn run-sensor -h household-server-2 -p 3003 -e +
    depends_on:
      - household-server-2
    networks:
      - 02-docker_parity_net

  sensor-server-3:
    build:
      context: .
      dockerfile: mock-sensor/Dockerfile
    command: yarn run-sensor -h household-server-3 -p 3004 -e +
    depends_on:
      - household-server-3
    networks:
      - 02-docker_parity_net

  sensor-server-4:
    build:
      context: .
      dockerfile: mock-sensor/Dockerfile
    command: yarn run-sensor -h household-server-4 -p 3005 -e +
    depends_on:
      - household-server-4
    networks:
      - 02-docker_parity_net

  sensor-server-5:
    build:
      context: .
      dockerfile: mock-sensor/Dockerfile
    command: yarn run-sensor -h household-server-5 -p 3006 -e +
    depends_on:
      - household-server-5
    networks:
      - 02-docker_parity_net

  sensor-server-6:
    build:
      context: .
      dockerfile: mock-sensor/Dockerfile
    command: yarn run-sensor -h household-server-6 -p 3007 -e -
    depends_on:
      - household-server-6
    networks:
      - 02-docker_parity_net

  sensor-server-7:
    build:
      context: .
      dockerfile: mock-sensor/Dockerfile
    command: yarn run-sensor -h household-server-7 -p 3008 -e -
    depends_on:
      - household-server-7
    networks:
      - 02-docker_parity_net

  sensor-server-8:
    build:
      context: .
      dockerfile: mock-sensor/Dockerfile
    command: yarn run-sensor -h household-server-8 -p 3009 -e -
    depends_on:
      - household-server-8
    networks:
      - 02-docker_parity_net

  sensor-server-9:
    build:
      context: .
      dockerfile: mock-sensor/Dockerfile
    command: yarn run-sensor -h household-server-9 -p 3010 -e -
    depends_on:
      - household-server-9
    networks:
      - 02-docker_parity_net

  sensor-server-10:
    build:
      context: .
      dockerfile: mock-sensor/Dockerfile
    command: yarn run-sensor -h household-server-10 -p 3011 -e -
    depends_on:
      - household-server-10
    networks:
      - 02-docker_parity_net

